language: node_js
node_js: lts/*
install:
  - npm install
script:
  - npm run public
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GH_TOKEN
  on:
    branch: resume
  local-dir: dist
